/**
 * Core types for the backtesting engine
 */

/**
 * OHLCV bar data for a single time period
 */
export interface Bar {
  time: number;      // Unix timestamp in milliseconds
  open: number;
  high: number;
  low: number;
  close: number;
  volume?: number;
}

/**
 * Multi-symbol bar data for a single time period
 */
export interface MultiBar {
  time: number;
  bars: Record<string, Bar>;
}

/**
 * Historical data for backtesting
 */
export interface BacktestData {
  symbols: string[];
  bars: MultiBar[];
  startDate: Date;
  endDate: Date;
}

/**
 * Trade signal generated by a strategy
 */
export interface Signal {
  type: 'buy' | 'sell' | 'close';
  symbol: string;
  quantity?: number;      // Absolute number of shares
  percentage?: number;    // Percentage of portfolio (0-1)
  price?: number;         // Limit price (optional, defaults to market)
  reason?: string;        // Optional description
}

/**
 * Executed trade record
 */
export interface Trade {
  id: string;
  symbol: string;
  side: 'buy' | 'sell';
  quantity: number;
  price: number;
  value: number;          // quantity * price
  commission: number;
  slippage: number;
  timestamp: number;
  reason?: string;
}

/**
 * Current position in a symbol
 */
export interface Position {
  symbol: string;
  quantity: number;       // Positive = long, negative = short
  averageCost: number;    // Average entry price
  currentPrice: number;   // Last known price
  marketValue: number;    // quantity * currentPrice
  unrealizedPnL: number;  // Current profit/loss
  unrealizedPnLPercent: number;
}

/**
 * Portfolio state at a point in time
 */
export interface PortfolioState {
  timestamp: number;
  cash: number;
  positions: Position[];
  totalValue: number;     // cash + sum of market values
  equity: number;         // Same as totalValue for long-only
}

/**
 * Equity curve data point
 */
export interface EquityPoint {
  time: number;
  equity: number;
  cash: number;
  drawdown: number;       // Current drawdown from peak (0 to -1)
  drawdownPercent: number;
}

/**
 * Backtest configuration
 */
export interface BacktestConfig {
  initialCapital: number;
  commission?: number;           // Per-share commission (default: 0)
  commissionPercent?: number;    // Percentage commission (default: 0)
  slippage?: number;             // Slippage percentage (default: 0.001 = 0.1%)
  maxPositionSize?: number;      // Max % of portfolio per position (default: 1 = 100%)
  allowShort?: boolean;          // Allow short selling (default: false)
  marginRequirement?: number;    // Margin requirement for shorts (default: 1.5)
}

/**
 * Performance metrics from a backtest
 */
export interface PerformanceMetrics {
  // Returns
  totalReturn: number;           // Total return as decimal (0.5 = 50%)
  totalReturnPercent: number;    // Total return as percentage
  cagr: number;                  // Compound annual growth rate
  
  // Risk metrics
  maxDrawdown: number;           // Maximum drawdown (negative)
  maxDrawdownPercent: number;    // Max drawdown as percentage
  maxDrawdownDuration: number;   // Days in max drawdown
  volatility: number;            // Annualized volatility
  sharpeRatio: number;           // Sharpe ratio (assuming 0% risk-free rate)
  sortinoRatio: number;          // Sortino ratio
  calmarRatio: number;           // CAGR / Max Drawdown
  
  // Trading metrics
  totalTrades: number;
  winningTrades: number;
  losingTrades: number;
  winRate: number;               // Winning trades / total trades
  profitFactor: number;          // Gross profit / gross loss
  averageWin: number;            // Average winning trade return
  averageLoss: number;           // Average losing trade return
  averageTrade: number;          // Average trade return
  largestWin: number;
  largestLoss: number;
  
  // Time metrics
  tradingDays: number;
  yearsTraded: number;
  exposurePercent: number;       // Percent of time in market
}

/**
 * Complete backtest results
 */
export interface BacktestResult {
  config: BacktestConfig;
  metrics: PerformanceMetrics;
  equityCurve: EquityPoint[];
  trades: Trade[];
  finalPortfolio: PortfolioState;
  startDate: Date;
  endDate: Date;
}

/**
 * Strategy context passed to onBar
 */
export interface StrategyContext {
  time: number;
  date: Date;
  bar: MultiBar;
  portfolio: PortfolioState;
  history: MultiBar[];
  barIndex: number;
  config: BacktestConfig;
}
